### ISSUE TITLE
Clarify relationship with fork

### ISSUE THREAD

**Issue by declension** [mujx/dhall-terraform#1]
Hi, thanks for the project, looking really useful.

I noticed there is a [much newer fork with an org of its own](https://github.com/dhall-terraform/dhall-terraform). Is this "official" now as best place to look / is there a plan to merge back here / or is it just another fork?

Thanks!

**Comment by mujx** [comment]
Hi @declension! I just learned about this fork. This seems to fall into "just another fork" category as I'm not affiliated with it. As I don't have much bandwidth currently to update `dhall-terraform` it probably is a good place too look for updates.
